# Generated by Django 4.2.16 on 2024-11-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_userprofile_mfa_secret"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
