# Generated by Django 4.2.16 on 2024-10-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
