# Generated by Django 4.2.16 on 2024-10-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_mfa_secret"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
