# Generated by Django 5.1.1 on 2024-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
